services:
  server:
    container_name: "snippet-operations"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - api
      - redis

  postgres:
    container_name: "snippet-operations-db"
    image: postgres:alpine
    environment:
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
    ports:
    - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - snippet_operations_data:/var/lib/postgresql/data

  api:
    container_name: "asset_service"
    image: "ghcr.io/austral-ingsis/snippet-asset-service:latest"
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "Asset Service"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    env_file:
      - .env

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  redis:
    container_name: "snippet_redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  snippet_operations_data:
  blob:
    external: false
